// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	reportcases "fgd-alterra-29/business/report_cases"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateCase provides a mock function with given fields: ctx, domain
func (_m *Repository) CreateCase(ctx context.Context, domain reportcases.Domain) (reportcases.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 reportcases.Domain
	if rf, ok := ret.Get(0).(func(context.Context, reportcases.Domain) reportcases.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(reportcases.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, reportcases.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReportForm provides a mock function with given fields: ctx
func (_m *Repository) GetReportForm(ctx context.Context) ([]reportcases.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []reportcases.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []reportcases.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reportcases.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
