// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	threadshares "fgd-alterra-29/business/thread_shares"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// ThreadShare provides a mock function with given fields: ctx, domain, id
func (_m *Repository) ThreadShare(ctx context.Context, domain threadshares.Domain, id int) (threadshares.Domain, error) {
	ret := _m.Called(ctx, domain, id)

	var r0 threadshares.Domain
	if rf, ok := ret.Get(0).(func(context.Context, threadshares.Domain, int) threadshares.Domain); ok {
		r0 = rf(ctx, domain, id)
	} else {
		r0 = ret.Get(0).(threadshares.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, threadshares.Domain, int) error); ok {
		r1 = rf(ctx, domain, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
